### ISSUE TITLE
Read Me is Inaccurate

### ISSUE THREAD

**Issue by rick-rheo** [immutable/imx-contracts#28]
Following instructions under "No Code Usage" fails and once I figured out (or think I did) what needs to change.  

npm install typescript and some other stuff,
rename .env.example to .env,  
provide DEPLOYER_MAINNET_PRIVATE_KEY  (even though I want to go to ropsten.  

It still fails because it seems its trying to deploy to the main ethereum even though the command I run is  "yarn hardhat run deploy/asset.ts --network ropsten"

If I leave out the mainnet key It complains about that.

This is the result

`No need to generate any newer typings.
Deploying Contract with the account: 0x75965652aC872E3A9fd3c9ad8E290473c23d763c
Account Balance: 63000
Error: insufficient funds for intrinsic transaction cost [ See: https://links.ethers.org/v5-errors-INSUFFICIENT_FUNDS ] (error={"name":"ProviderError","code":-32000,"_isProviderError":true}, method="sendTransaction", transaction=undefined, code=INSUFFICIENT_FUNDS, version=providers/5.6.2)
    at Logger.makeError (/Users/rick/dev/projects/weav/backend/nftPlayground/imx-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
    at Logger.throwError (/Users/rick/dev/projects/weav/backend/nftPlayground/imx-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
    at checkError (/Users/rick/dev/projects/weav/backend/nftPlayground/imx-contracts/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:81:16)
    at /Users/rick/dev/projects/weav/backend/nftPlayground/imx-contracts/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:243:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  reason: 'insufficient funds for intrinsic transaction cost',
  code: 'INSUFFICIENT_FUNDS',
  error: ProviderError: insufficient funds for gas * price + value
      at HttpProvider.request (/Users/rick/dev/projects/weav/backend/nftPlayground/imx-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:74:19)
      at LocalAccountsProvider.request (/Users/rick/dev/projects/weav/backend/nftPlayground/imx-contracts/node_modules/hardhat/src/internal/core/providers/accounts.ts:182:36)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async EthersProviderWrapper.send (/Users/rick/dev/projects/weav/backend/nftPlayground/imx-contracts/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20),
  method: 'sendTransaction',
  transaction: undefined
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
imx-contracts[main]$ yarn hardhat run deploy/asset.ts --network ropsten
yarn run v1.22.18
`

**Comment by bkotrys** [comment]
I have exactly the same issue? Anyone found solution?

**Comment by avanaur** [comment]
It seems the issue is that the IMX address run out of balance in ropsten network. Check here.
https://ropsten.etherscan.io/address/0x75965652ac872e3a9fd3c9ad8e290473c23d763c

Try transferring some ETH or get some from faucet before creating your contract. That worked for me.

**Comment by enrickla** [comment]
I had it working by removing `DEPLOYER_MAINNET_PRIVATE_KEY=` from `.env` and the mainnet entry in `hardhat.config.ts`

**Comment by lancety** [comment]
go to ALCHEMY to apply for ALCHEMY_API_KEY
go to your metamask get private key and set on both 
DEPLOYER_ROPSTEN_PRIVATE_KEY 
DEPLOYER_MAINNET_PRIVATE_KEY

I dont think harthat command 'network' ropsten will make the command deploy to mainnet,  also it is not necessary to remove any code from the config file
After I did what has been asked by the readme of this repo, and updated above 3 keys, my deploy is suceess.

Hope this is helpful

**Comment by lancety** [comment]
more complete guide here https://docs.x.immutable.com/docs/zero-to-hero-nft-minting
